import { Inter } from "next/font/google";
import "./globals.css";
import { Nanum_Gothic } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const gothic = Nanum_Gothic({ subsets: ["latin"], weight: "700" });

export const metadata = {
  title: "TodayEat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
